# Generated by Django 6.0.6 on 2026-06-17 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Refineries',
            },
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('_tags', models.TextField(db_column='tags', default='[]')),
                ('source_document', models.FileField(blank=True, null=True, upload_to='sop_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_app.department')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_sops', to=settings.AUTH_USER_MODEL)),
                ('refinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_app.refinery')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_app.processunit')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('approval_request', 'Approval Request'), ('approved', 'SOP Approved'), ('rejected', 'SOP Rejected'), ('draft_reminder', 'Draft Reminder'), ('info', 'Info')], default='info', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sop_app.sop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=100)),
                ('approval_type', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain', to='sop_app.sop')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='SOPSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sop_app.sop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SOPComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('chart', 'Chart'), ('image', 'Image'), ('table', 'Table')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='sop_images/')),
                ('image_url', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('chart_title', models.CharField(blank=True, max_length=300)),
                ('chart_desc', models.TextField(blank=True)),
                ('_table_rows', models.TextField(db_column='table_rows', default='[]')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sop_app.sopsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
