# Generated by Django 6.0.6 on 2026-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopcomponent',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('step', 'Numbered Steps'), ('chart', 'Chart'), ('image', 'Image'), ('table', 'Table')], max_length=10),
        ),
    ]
